### ISSUE TITLE
 java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again

### ISSUE THREAD

**Issue by Spikoss** [luqinmao/TomatoIt#3]
executorService.schedule(this::invalidateWrap, 233, TimeUnit.MICROSECONDS);
这行报错

**Comment by heweiquan** [comment]
我也遇到这个问题。直接运行，在首页呆个几分钟，就出现崩溃了。
<img src="https://user-images.githubusercontent.com/13057762/36008777-e9348e1a-0d83-11e8-9cfd-17bf728e3f11.png" width=300 />
![image](https://user-images.githubusercontent.com/13057762/36008793-f27205f2-0d83-11e8-8e4c-657873d59ed9.png)

**Comment by luqinmao** [comment]
@Spikoss @heweiquan   我之前把自定义View DynamicWave中的 ScheduledExecutorService创建放在了onDraw()方法里面，导致不断创建对象，改过来了，现在不会了吧？
