### ISSUE TITLE
集成项目经常出现404

### ISSUE THREAD

**Issue by duanhai123** [luqinmao/TomatoIt#9]
集成项目经常出现404,但是我单用okgo的话没有问题

**Comment by luqinmao** [comment]
@duanhai123 什么情况，可以截下图吗

**Comment by duanhai123** [comment]
好的我去截图给您看一下

**Comment by duanhai123** [comment]
昨天一直打印吐司404,今天突然没有了

**Comment by duanhai123** [comment]
![img_20180824_105839](https://user-images.githubusercontent.com/21290034/44562617-ee4bb880-a78c-11e8-8e8a-5ef687dfc0f4.jpg)

**Comment by duanhai123** [comment]
一直报这个

**Comment by luqinmao** [comment]
你自己的服务器接口出问题了， @duanhai123

**Comment by duanhai123** [comment]
但是app没有什么问题,我用okgo也不会报这个出来有什么办法解决吗

**Comment by luqinmao** [comment]
你要看看你的接口是出现什么问题了，自己测试一下接口或者问一下后端的人 @duanhai123

**Comment by duanhai123** [comment]
谢谢我找到了
